##Datenbereinigung - Projekt: Eniac_Rabattstrategie

Version 1

In [70]:
import pandas as pd

#1-Einlesen der Datenbanken (Original)

---

##1- orderlines.csv

In [71]:
url = "https://drive.google.com/file/d/1hm1PduaHt3pfKZThkinjeHpaVCpt07rH/view?usp=drive_link" # orderlines.csv
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
df_orderlines = pd.read_csv(path)

##2- orders.csv

In [72]:
url = "https://drive.google.com/file/d/1s2EJj2-3l2K4lpJKLRabm6LAWFNL9Vof/view?usp=drive_link" # orders.csv
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
df_orders = pd.read_csv(path)

##3- brands.csv

In [73]:
url = "https://drive.google.com/file/d/1RXem7FCdBTXHBVtJeKOotaSavC14dIkM/view?usp=drive_link" # brands.csv
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
df_brands = pd.read_csv(path)

##4- products.csv

In [74]:
url = "https://drive.google.com/file/d/1lH3mqhvdrddBoRxFX78BKR0RURkmbjh1/view?usp=drive_link" # products.csv
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
df_products = pd.read_csv(path)

#2- Copy erstellen

In [75]:
#orderlines
copy_orderlines = df_orderlines.copy()

In [76]:
#orders
copy_orders = df_orders.copy()

In [77]:
#Brands
copy_brands = df_brands.copy()

In [78]:
#products
copy_products = df_products.copy()

In [79]:
# Spaltenname anpassen, um ihn an die anderen Datensätze anzupassen.
copy_orders.rename(columns={'order_id':'id_order'}, inplace=True)

In [80]:
# Die Spalte "product_id" entfernen,
# da sie ausschließlich den Wert 0 enthält und für die weitere Analyse nicht benötigt wird.

copy_orderlines =copy_orderlines.drop(columns=['product_id'])

#3- Bereinigung der Zeichenketten (String-Spalten)

 Entfernen von führenden und nachgestellten Leerzeichen, da diese zu Fehlern bei Vergleichen und Zusammenführungen führen können.
 Führende und nachgestellte Leerzeichen aus allen Textspalten entfernen.

##1- orders

In [81]:
str_cols = [col for col in copy_orders.columns if copy_orders[col].dtype == 'object']
for col in str_cols :
  copy_orders[col] = copy_orders[col].str.strip()

##2- orderlines

In [82]:
str_cols = [col for col in copy_orderlines.columns if copy_orderlines[col].dtype == 'object']
for col in str_cols :
  copy_orderlines[col] = copy_orderlines[col].str.strip()

##3- pruducts

In [83]:
str_cols = [col for col in copy_products.columns if copy_products[col].dtype == 'object']
for col in str_cols :
  copy_products[col] = copy_products[col].str.strip()

##4- brands

In [84]:
str_cols = [col for col in copy_brands.columns if copy_brands[col].dtype == 'object']
for col in str_cols :
  copy_brands[col] = copy_brands[col].str.strip()

##products.csv

#4- Exploration der Daten

##1- [.info,.sum], usw.

In [85]:
copy_products.isna().sum()

sku             0
name            0
desc            7
price          46
promo_price     0
in_stock        0
type           50
dtype: int64

In [86]:
copy_orders.isna().sum()

id_order        0
created_date    0
total_paid      5
state           0
dtype: int64

In [87]:
copy_orderlines.isna().sum()

id                  0
id_order            0
product_quantity    0
sku                 0
unit_price          0
date                0
dtype: int64

In [88]:
copy_brands.isna().sum()

short    0
long     0
dtype: int64

**Ergebnis:**


1.   products_Spalte
  * desc hat 7 null Werte
  * price hat 46 null Werte
  * Type hat 50 fehlende Werte
2.   orders_Spalte
  * unit_price hat 5 null werte

In [89]:
copy_orderlines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293983 entries, 0 to 293982
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                293983 non-null  int64
 1   id_order          293983 non-null  int64
 2   product_quantity  293983 non-null  int64
 3   sku               293983 non-null  object
 4   unit_price        293983 non-null  object
 5   date              293983 non-null  object
dtypes: int64(3), object(3)
memory usage: 13.5+ MB

In [90]:
copy_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226909 entries, 0 to 226908
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id_order      226909 non-null  int64
 1   created_date  226909 non-null  object
 2   total_paid    226904 non-null  float64
 3   state         226909 non-null  object
dtypes: float64(1), int64(1), object(2)
memory usage: 6.9+ MB

In [91]:
copy_brands.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   short   187 non-null    object
 1   long    187 non-null    object
dtypes: object(2)
memory usage: 3.1+ KB

In [92]:
copy_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19326 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          19326 non-null  object
 1   name         19326 non-null  object
 2   desc         19319 non-null  object
 3   price        19280 non-null  object
 4   promo_price  19326 non-null  object
 5   in_stock     19326 non-null  int64
 6   type         19276 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.0+ MB

#5- Doppelte Zeilen entfernen

##1- Duplikate prüfen

In [93]:
copy_orders.duplicated().sum()

np.int64(0)

In [94]:
copy_orderlines.duplicated().sum()

np.int64(0)

In [95]:
copy_products.duplicated().sum()

np.int64(8746)

In [96]:
num_duplicated = copy_products.duplicated().sum()
total_rows = copy_products.shape[0]
percent_duplicated = (100 * num_duplicated / total_rows)
print(f"{percent_duplicated:.2f}% der Zeilen sind Duplikate")

45.26% der Zeilen sind Duplikate

In [97]:
num_duplicated = copy_products.duplicated().value_counts(normalize=True)
num_duplicated

False    0.547449
True     0.452551
Name: proportion, dtype: float64

**Ergebnis:**
- über 45% der Zeilen fehlen.

##2- Duplikate entfernen

**Ergebnis**:

In keinem der beiden DataFrames gibt es doppelte Zeilen.

In [98]:
# Duplikate löschen
copy_products = copy_products.drop_duplicates()

In [99]:
# mit shape prüfen wieviele Zeilen nach .drop_duplicates() übrig sind
copy_products.shape

(10580, 7)

**Ergebnis:**

- Nach Duplikat-Entfernung hat products 10.580 Zeilen, davon 377 (3,56%) mit korrupten Mehrfach-Punkt-Preisen.

Drei Optionen, mit Vor-/Nachteilen:

- Löschen (377 Zeilen, 3,56%) , aber man verliert die Produkte komplett aus der Analyse (auch aus orderlines-Verknüpfungen über sku)
- Muster rückentwickeln => ein paar Beispiele genau anschauen: ist es immer "letzter Punkt = Dezimaltrennzeichen, Rest = Tausendertrenner"? Falls ja, lässt sich das mathematisch korrigieren (z.B. 26.155.941 → 26155.941)
- Auf NaN setzen — Wert als fehlend markieren statt Zeile zu löschen, Produkt bleibt erhalten für andere Analysen (Name, Kategorie etc.), nur price fehlt

**Ergebnis:**

=>Zeilen wurden gelöscht

#6- NaN_Einträge

##1- NaN_Einträge prufen

In [100]:
copy_orders.isna().sum()

id_order        0
created_date    0
total_paid      5
state           0
dtype: int64

In [101]:
copy_orderlines.isna().sum()

id                  0
id_order            0
product_quantity    0
sku                 0
unit_price          0
date                0
dtype: int64

In [102]:
copy_products.isna().sum()

sku             0
name            0
desc            7
price          46
promo_price     0
in_stock        0
type           50
dtype: int64

**Ergebnis:**

1.   products_Spalte
  * desc hat 7 null Werte
  * price hat 46 null Werte
  * Type hat 50 fehlende Werte
2.   orders_Spalte
  * unit_price hat 5 null werte

##2- NaN_Einträge bearbeiten

###1-products

####1- Desc

In [103]:
# Filtert copy_products auf alle Zeilen, bei denen desc fehlt (NaN).
copy_products.loc[copy_products['desc'].isna(), :]

,sku,name,desc,price,promo_price,in_stock,type
16126,WDT0211-A,"Open - Purple 2TB WD 35 ""PC Security Mac hard ...",NaN,107,814.659,0,1298
16128,APP1622-A,Open - Apple Smart Keyboard Pro Keyboard Folio...,NaN,1.568.206,1.568.206,0,1298
17843,PAC2334,Synology DS718 + NAS Server | 10GB RAM,NaN,566.35,5.659.896,0,12175397
18152,KAN0034-A,Open - Kanex USB-C Gigabit Ethernet Adapter Ma...,NaN,29.99,237.925,0,1298
18490,HTE0025,Hyper Pearl 1600mAh battery Mini USB Mirror an...,NaN,24.99,22.99,1,1515
18612,OTT0200,OtterBox External Battery Power Pack 20000 mAHr,NaN,79.99,56.99,1,1515
18690,HOW0001-A,Open - Honeywell thermostat Lyric zonificador ...,NaN,199.99,1.441.174,0,11905404

In [104]:
# Bei allen Zeilen mit fehlendem desc den Wert aus name einsetzen.
copy_products.loc[copy_products['desc'].isna(), 'desc'] = copy_products.loc[copy_products['desc'].isna(), 'name']

In [105]:
#Die Anzahl der Zeilen, bei denen desc fehlt (NaN) zählen.
copy_products['desc'].isna().sum()

np.int64(0)

####2-price

In [106]:
copy_products = copy_products.dropna(subset='price')

####3- type

In der Spalte type wurden 50 fehlende Werte (NaN) gefunden.

Unser Team hat diese Datensätze analysiert und festgestellt, dass ein großer Teil davon Produkte von Apple betrifft.

Da nur wenige Datensätze betroffen sind und kein ausreichender Hinweis für eine korrekte Nachtragung des Produkttyps vorliegt, haben wir uns bewusst gegen das Löschen oder Ersetzen dieser Werte entschieden.

Die Datensätze bleiben daher unverändert erhalten, um keinen Informationsverlust zu verursachen.

#####1- Fehlende Werte identifizieren

In [107]:
type_mask = copy_products['type'].isna()
type_nan = copy_products.loc[type_mask,:]
type_nan.shape[0]

50

#####2- Auswirkungen auf Bestellungen analysieren

In [108]:
orderlines_type_merged = copy_orderlines.merge(type_nan, on='sku', how='inner')
orderlines_type_merged.shape[0]

184

In [109]:
Completed = copy_orders.merge(orderlines_type_merged, on='id_order', how='inner')
mask = Completed['state'].isin(['Completed'])
Completed.loc[mask,:].shape[0]

13

Die Analyse zeigt, dass nur 13 Bestellungen betroffen wären.

Da keine zuverlässige Methode zur Bestimmung des fehlenden Produkttyps vorhanden ist, wurden die Datensätze nicht gelöscht.

Stattdessen wurden die fehlenden Werte in der Spalte **type** mit **„unbekannt“** ersetzt. Dadurch enthält die Tabelle keine NaN-Werte mehr und kann in den weiteren Analysen konsistent verwendet werden.

In [110]:
copy_products.loc[type_mask,'type'] = 'unbekannt'

### 2- Orders

#### `total_paid`

In [111]:
total_paid_mask = copy_orders['total_paid'].isna()
copy_orders.loc[total_paid_mask,:'total_paid'].shape[0]

5

In [112]:
copy_orders['total_paid'].isna().value_counts(normalize=True)

total_paid
False    0.999978
True     0.000022
Name: proportion, dtype: float64

**Ergebnis:**

- Weniger als 0.002% betroffen --> löschen

In [113]:
copy_orders = copy_orders.dropna(subset='total_paid')

#7- Digitale Spatten

##1- products `Price` Spalte


Im Datensatz wurden fehlerhafte Preisformate gefunden (z. B. `34.56.546`), die nicht direkt in numerische Werte umgewandelt werden konnten.

Anstatt diese Datensätze zu löschen, entschied sich unser Team für eine Korrektur der Preisangaben. Der Grund dafür war, dass diese Produkte mit **4150 Bestellpositionen** verknüpft sind, darunter **799 abgeschlossene Bestellungen (Completed)**.

Daher wurde die erste fehlerhafte Trennstelle entfernt, die Preise auf zwei Dezimalstellen gerundet und anschließend in numerische Werte umgewandelt.

### 1- Fehlerhafte Preise identifizieren
Zunächst werden alle Produkte identifiziert, deren Preis mehr als einen Punkt enthält.

In [114]:
price_mask = copy_products['price'].str.count(r'\.') > 1
copy_products.loc[price_mask, 'price'].shape[0]

377

### 2-   Betroffene Bestellungen analysieren

Anschließend wird geprüft, wie viele Bestellpositionen und Bestellungen von diesen Produkten betroffen sind.

In [115]:
price_mask = copy_products['price'].str.count(r'\.') > 1
sku_list = copy_products.loc[price_mask, 'sku']
orderlines_mask = copy_orderlines['sku'].isin(sku_list)
umsätze_zwei_punkte=copy_orderlines.loc[orderlines_mask, :]
umsätze_zwei_punkte.shape[0]

4150

### 3-⁠ ⁠Auswirkungen auf abgeschlossene Bestellungen

Zur Entscheidungsfindung wird untersucht, wie viele der betroffenen Bestellungen bereits abgeschlossen wurden.

In [116]:
orders_umsätse_merged = copy_orders.merge(umsätze_zwei_punkte, on='id_order',how='inner')
orders_umsätse_merged
orders_umsätse_merged['state'].value_counts()

state
Shopping Basket    2246
Completed           799
Place Order         601
Pending             258
Cancelled           246
Name: count, dtype: int64

### 4- Preisformat korrigieren

Die erste fehlerhafte Trennstelle wird entfernt, sodass die Preise anschließend als numerische Werte gespeichert werden können.

In [117]:
copy_products.loc[price_mask, 'price'] = copy_products.loc[price_mask, 'price'].str.replace('.','',1)

### 5- Datentyp umwandeln

Nach der Korrektur wird die Spalte in einen numerischen Datentyp umgewandelt.

In [118]:
copy_products['price'] = pd.to_numeric(copy_products['price'])

### 6- Preise an Euro-Format anpassen

Zum Schluss werden die betroffenen Preise auf zwei Dezimalstellen angepasst.

In [119]:
price_mask = copy_products.price.astype(str).str.contains(r"\d+\.\d{3}")
copy_products.loc[price_mask ,'price'] =round(copy_products.loc[price_mask , 'price'] / 10, 2)

##2- products `Promo_Price` Spalte

In [120]:
#in promo_price
# Werte prüfen welche von 2 oder 3 Dezimalstellen betroffen sind

promo_problems_number = copy_products.loc[(copy_products.promo_price.str.contains(r"\d+\.\d+\.\d+"))|(copy_products.promo_price.str.contains(r"\d+\.\d{3,}")), :].shape[0]
promo_problems_number

9691

In [121]:
 print(f"The column promo_price has in total {promo_problems_number} wrong values. This is {round(((promo_problems_number / copy_products.shape[0]) * 100), 2)}% of the rows of the DataFrame")

The column promo_price has in total 9691 wrong values. This is 92.0% of the rows of the DataFrame

**Ergebnis:**

- Die Spalte promo_price enthält 542 falsche Werte
- Das sind 5.12 % die fehlerhaft sind.

In [122]:
copy_products = copy_products.drop(columns=["promo_price"])

## 3- orderlines `unit_price` Spalte


Im Datensatz wurden fehlerhafte Preisformate gefunden (z. B. `34.56.546`), die nicht direkt in numerische Werte umgewandelt werden konnten.

Anstatt diese Datensätze zu löschen, entschied sich unser Team für eine Korrektur der Preisangaben. Der Grund dafür war, dass diese Produkte mit **36169 Bestellpositionen** verknüpft sind, darunter **3561 abgeschlossene Bestellungen (Completed)**.

Daher wurde die erste fehlerhafte Trennstelle entfernt, die Preise auf zwei Dezimalstellen gerundet und anschließend in numerische Werte umgewandelt.

### 1- Fehlerhafte unit_Preise identifizieren

Betroffene Bestellungen analysieren.
Zunächst werden alle Produkte identifiziert, deren Preis mehr als einen Punkt enthält.

In [123]:
unit_price_mask = copy_orderlines['unit_price'].str.count(r'\.') > 1
umsätze_zwei_punkte = copy_orderlines.loc[unit_price_mask,:]
copy_orderlines.loc[unit_price_mask, 'unit_price'].shape[0]

36169

### 3-⁠ ⁠Auswirkungen auf abgeschlossene Bestellungen

Zur Entscheidungsfindung wird untersucht, wie viele der betroffenen Bestellungen bereits abgeschlossen wurden.

In [124]:
orders_umsätse_merged = copy_orders.merge(umsätze_zwei_punkte, on='id_order',how='inner')
orders_umsätse_merged
orders_umsätse_merged['state'].value_counts()

state
Shopping Basket    24425
Place Order         5245
Completed           3561
Cancelled           1802
Pending             1104
Name: count, dtype: int64

### 4- Preisformat korrigieren

Die erste fehlerhafte Trennstelle wird entfernt, sodass die Preise anschließend als numerische Werte gespeichert werden können.

In [125]:
copy_orderlines.loc[unit_price_mask, 'unit_price'] = copy_orderlines.loc[unit_price_mask, 'unit_price'].str.replace('.','',1)


### 5- Datentyp umwandeln

Nach der Korrektur wird die Spalte in einen numerischen Datentyp umgewandelt.

In [126]:
copy_orderlines['unit_price'] = pd.to_numeric(copy_orderlines['unit_price'])

### 6- Preise an Euro-Format anpassen

Zum Schluss werden die betroffenen Preise auf zwei Dezimalstellen angepasst.

In [127]:
unit_price_mask = copy_orderlines.unit_price.astype(str).str.contains(r"\d+\.\d{3}")
copy_orderlines.loc[unit_price_mask ,'unit_price'] =round(copy_orderlines.loc[unit_price_mask , 'unit_price'] / 10, 2)

#7- Datum Spalten

Die Datum_Spalten  werden in den Datentyp `datetime` umgewandelt, damit Datums- und Zeitoperationen (z. B. Filtern, Gruppieren oder zeitbasierte Analysen) korrekt durchgeführt werden können.

##1- orders

In [128]:
copy_orders["created_date"] = pd.to_datetime(copy_orders["created_date"])

##2- orderlines

In [129]:
copy_orderlines["date"] = pd.to_datetime(copy_orderlines["date"])

Ergebnis:

- Wurde zum Datentyp Datum/Uhrzeit. Hinweis später erneut prüfen.

#8- Exploration nach der Bereinigung

In [130]:
copy_orders.info()

<class 'pandas.core.frame.DataFrame'>
Index: 226904 entries, 0 to 226908
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id_order      226904 non-null  int64
 1   created_date  226904 non-null  datetime64[ns]
 2   total_paid    226904 non-null  float64
 3   state         226904 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 8.7+ MB

In [131]:
copy_orderlines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293983 entries, 0 to 293982
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                293983 non-null  int64
 1   id_order          293983 non-null  int64
 2   product_quantity  293983 non-null  int64
 3   sku               293983 non-null  object
 4   unit_price        293983 non-null  float64
 5   date              293983 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 13.5+ MB

In [132]:
copy_products.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10534 entries, 0 to 19325
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sku       10534 non-null  object
 1   name      10534 non-null  object
 2   desc      10534 non-null  object
 3   price     10534 non-null  float64
 4   in_stock  10534 non-null  int64
 5   type      10534 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 576.1+ KB

In [133]:
copy_brands.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   short   187 non-null    object
 1   long    187 non-null    object
dtypes: object(2)
memory usage: 3.1+ KB

#9- Export der bereinigten Datensätze

Nach Abschluss aller Bereinigungs- und Vorverarbeitungsschritte werden die bereinigten Datensätze als CSV-Dateien exportiert.

Diese Dateien dienen als Grundlage für die nächste Projektphase (Analyse und Visualisierung).

In [135]:
#Bereinigte Daten speichern in Drive

from google.colab import files

copy_orders.to_csv("orders_cl.csv", index=False)
files.download("orders_cl.csv")

copy_orderlines.to_csv("orderlines_cl.csv", index=False)
files.download("orderlines_cl.csv")

copy_products.to_csv("products_cl.csv", index=False)
files.download("products_cl.csv")

copy_brands.to_csv("branbs_cl.csv", index=False)
files.download("brands_cl.csv")