In [ ]:
# Die Spalte "product_id" entfernen,
# da sie ausschließlich den Wert 0 enthält und für die weitere Analyse nicht benötigt wird.

orderlines_df =orderlines_df.drop(columns=['product_id'])

 Spaltennamen vereinheitlichen

In [ ]:
# Spaltenname anpassen, um ihn an die anderen Datensätze anzupassen.
orders_df.rename(columns={'order_id':'id_order'}, inplace=True)

# **Products**

# Erstellung einer zusammengeführten Analysetabelle

Für die weitere Analyse wurden die Tabellen **orderlines** und **products** über die Spalte **sku** zusammengeführt.

Anschließend wurde eine neue Variable **discount_percent** berechnet. Sie beschreibt den prozentualen Rabatt eines Produkts zum Zeitpunkt der Bestellung. Grundlage für die Berechnung ist der Vergleich zwischen dem ursprünglichen Produktpreis (**price**) und dem tatsächlichen Verkaufspreis (**unit_price**).

## 1- orderlines und products zusammenführen

In [ ]:
orderlines_products_merged = orderlines_df.merge(products_df, on='sku',how='inner')
orderlines_products_merged.shape[0]

214922

## 2- Rabatt pro Bestellung berechnen

In [ ]:
orderlines_products_merged['discount_percent'] = 100 - round((orderlines_products_merged['unit_price'] * 100) /
                                                        orderlines_products_merged['price'], 0)
orderlines_products_merged.head(5)

,id,id_order,product_quantity,sku,unit_price,date,name,desc,price,in_stock,type,discount_percent
0,1119109,299539,1,OTT0133,18.99,2017-01-01 00:07:19,Otterbox iPhone Case Symmetry 2.0 SE / 5s / 5 ...,resistant cover and thin beveled edges for iPh...,34.99,0,11865403,45.73
1,1119110,299540,1,LGE0043,399.00,2017-01-01 00:19:45,"27UD58-B LG Monitor 27 ""4K UHD DisplayPort",Monitor for gamers and multimedia professional...,429.00,0,1296,6.99
2,1119111,299541,1,PAR0071,474.05,2017-01-01 00:20:57,Parrot Bebop 2 White + Command FLYPAD and FPV ...,cuadricóptero wireless remote control with 25 ...,699.00,0,11905404,32.18
3,1119112,299542,1,WDT0315,68.39,2017-01-01 00:51:40,"Blue WD 2TB Hard Drive 35 ""Mac and PC",Internal Hard Drive Western Digital 2TB 3.5-in...,79.00,0,12655397,13.43
4,1119113,299543,1,JBL0104,23.74,2017-01-01 01:06:38,Gray Bluetooth Speaker JBL GO,Compact Bluetooth Handsfree for iPhone iPad an...,29.90,1,5398,20.60

Der Rabatt wird mit folgender Formel berechnet:

**Rabatt (%) = 100 − (unit_price × 100 / price)**

Positive Werte bedeuten einen Rabatt gegenüber dem ursprünglichen Produktpreis.
Negative Werte zeigen, dass der Verkaufspreis zum Bestellzeitpunkt höher war als der aktuell gespeicherte Produktpreis.

## 3- Bestellinformationen ergänzen

Mit orders zusammenführen

In [ ]:
orders_orderlines_products_merged =orders_df.merge(orderlines_products_merged, on='id_order', how='inner')
orders_orderlines_products_merged.head()

,id_order,created_date,total_paid,state,id,product_quantity,sku,unit_price,date,name,desc,price,in_stock,type,discount_percent
0,241319,2017-01-02 13:35:40,44.99,Cancelled,1121139,1,JBL0123,44.99,2017-01-02 12:26:59,JBL T450 Bluetooth BT Headset White,Wireless headphones with folding design with 1...,49.95,1,5384,9.93
1,241423,2017-11-06 13:10:02,136.15,Completed,1398738,1,LAC0212,129.16,2017-11-06 12:47:20,LaCie Porsche Design Desktop Drive 4TB USB 3.0...,External Hard Drive 4TB 35-inch USB 3.0 for Ma...,139.99,1,11935397,7.74
2,242832,2017-12-31 17:40:03,15.76,Completed,1529178,1,PAR0074,10.77,2017-12-31 17:26:40,Parrot 550mAh battery for MiniDrones,550mAh rechargeable battery for Parrot minidrones,17.99,0,11905404,40.13
3,243330,2017-02-16 10:59:38,84.98,Completed,1181923,1,OWC0074,77.99,2017-02-15 17:07:44,Mac OWC Memory 8GB 1066MHZ DDR3 SO-DIMM,8GB RAM Mac mini iMac MacBook and MacBook Pro ...,99.99,1,1364,22.00
4,243784,2017-11-24 13:35:19,157.86,Cancelled,1437153,3,PHI0080,51.29,2017-11-24 13:27:41,Philips HUE White Ambience Pack 2 GU10 bulbs,Pack of two bulbs with different shades of whi...,59.95,1,11905404,14.45

In [ ]:
orders_orderlines_products_merged = orders_orderlines_products_merged.loc[orders_orderlines_products_merged['state'].isin(['Completed','Pending','Place Order']),:]

## 4- Verteilung der Bestellstatus

In [ ]:
bestellungen = orders_orderlines_products_merged['state'].value_counts()
bestellungen

state
Shopping Basket    107417
Completed           56402
Place Order         27450
Pending             16963
Cancelled            6506
Name: count, dtype: int64

Zum Abschluss wurde die Anzahl der Bestellungen je Status ermittelt.
Diese Information dient als Grundlage für die nachfolgenden Analysen der Rabattverteilung.

# Export der bereinigten Datensätze

Nach Abschluss aller Bereinigungs- und Vorverarbeitungsschritte werden die bereinigten Datensätze als CSV-Dateien exportiert.

Diese Dateien dienen als Grundlage für die nächste Projektphase (Analyse und Visualisierung).

In [ ]:
from google.colab import files

orders_df.to_csv("orders_cl_02.csv", index=False)
files.download("orders_cl_02.csv")

orderlines_df.to_csv("orderlines_cl_02.csv", index=False)
files.download("orderlines_cl_02.csv")

products_df.to_csv("products_cl_02.csv", index=False)
files.download("products_cl_02.csv")

brands_df.to_csv("brands_cl.csv_02", index=False)
files.download("brands_cl.csv_02")